### ISSUE TITLE
Compatibility with ESP-IDF 3.3 (stable)

### ISSUE THREAD

**Issue by sosaucily** [mrxa13/esp-baresip#2]
When compiling this package in an esp-idf/adf project using the 3.3 version of idf, errors occur with the SoC component of the esp-idf library. 

For example:
```
esp-idf/components/soc/esp32/include/soc/cpu.h:36:5: error: 'asm' undeclared (first use in this function)
     asm volatile ("mov %0, sp;" : "=r" (sp));
```

3.3 is the stable build of esp-idf. Not sure why this is happening, but i'll dig in a bit today.

**Comment by sosaucily** [comment]
Actually, it seems the flag 
```-std=c99```
in the component.mk file is causing this, as discussed here:
https://stackoverflow.com/questions/35131350/error-asm-undeclared-first-use-in-this-function

Without this std=c99 flag it compiles with esp-idf 3.3. Can I make a PR?

**Comment by sosaucily** [comment]
I also had trouble with this flag, and needed to comment it out in order to remove some overwhelming number of warnings during compilation.

CFLAGS	+= -Wsign-compare

**Comment by fAuernigg** [comment]
Yes please make a PR.
Also ignoring a few warnings sounds good. Especially Wsign-compare sounds ok to me.
